apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nztb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nztb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nztb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nztb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nztb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hxtx-tenant/rhtap-demo-app/hacbs-test-project-nztb@sha256:cca7359ba966b578cbd6145d6932f657bf1baf93b6f8e4dbc9ff72507794d301
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
