apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nztb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hxtx-tenant/rhtap-demo-app/hacbs-test-project-nztb@sha256:cca7359ba966b578cbd6145d6932f657bf1baf93b6f8e4dbc9ff72507794d301
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
